<a href="https://colab.research.google.com/github/AnishShrestha09/assignment/blob/main/numpy12.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
# A bank account has the following transactions:
import numpy as np

transactions = np.array([
5000, -2000, 15000, -4500, 7000,
-12000, 25000, -3000, 8000, -18000,
4500, 22008, -6008, 9000, -2500
])

# Extract deposits.
print(transactions[transactions > 0 ])


# Extract withdrawals.
print(transactions[transactions < 0 ])


# Calculate total deposits and withdrawals.
print(np.sum(transactions[transactions > 0 ]))
print(np.sum(transactions[transactions < 0 ]))
sum_pos = np.sum(transactions[transactions > 0 ])
sumneg = np.absolute(np.sum(transactions[transactions < 0 ]))


# Calculate absolute transaction values.
total_transaction = sum_pos + sumneg
print(total_transaction)


# Calculate net transaction amount.
a = np.sum(transactions[transactions > 0 ])-np.sum(transactions[transactions < 0 ])
print(a)


[ 5000 15000  7000 25000  8000  4500 22008  9000]
[ -2000  -4500 -12000  -3000 -18000  -6008  -2500]
95508
-48008
143516
143516


In [11]:
# Find transactions whose absolute value is above the average absolute transaction.
mean = np.mean(np.absolute(transactions))
print(transactions[np.absolute(transactions) > mean])

# Find the largest deposit.
print(np.max(transactions))

# Find the largest withdrawal.
print(np.min(transactions))

# Create labels "Credit" and "Debit".
np.where(transactions > 0 ,"credit","debit")

# Find pergentage of transactions whose absolute value is greater than ₹10,000.
absolute_transaction = np.absolute(transactions)
a = len(transactions[transactions > 10000])
total = len(transactions)
percentage = a/total * 100
print(percentage)

# Reshape the data into 3 X 5.
b = transactions.reshape(3,5)
print(b)

# Calculate total transaction value for each row.
absolute_b = np.absolute(b)
print(np.sum(absolute_b, axis = 1))





[ 15000 -12000  25000 -18000  22008]
25000
-18000
20.0
[[  5000  -2000  15000  -4500   7000]
 [-12000  25000  -3000   8000 -18000]
 [  4500  22008  -6008   9000  -2500]]
[33500 66000 44016]
